### ISSUE TITLE
Could this be used on other systems?

### ISSUE THREAD

**Issue by adam-ainsworth** [jbilander/SDBox-v2#8]
Since this connects via the parallel port, presumably this could be used on other retro systems if drivers were written?

I'm thinking mainly ST, Apple Mac 68k & DOS PC but I guess 8-bit machines aren't out of the question?

**Comment by jbilander** [comment]
Hi, yes if you write a driver for your system it should be possible as long as the machine follows the Centronics standard  pinout and is bi-directional and has the ability to program individual bits as inputs and outputs including the BUSY,POUT and SELECT-pins. More info here:
https://github.com/jbilander/sdbox/blob/master/technical-info-parallel-port.md

I think this user with nick _Masteries_ below did it for Atari ST. Unfortunately I don't think he honors the copyleft GPL-license and shares his code with the community which is a requirement in GPL.
https://www.atari-forum.com/viewtopic.php?t=40018

you can see he got the idea from us here:
https://eab.abime.net/showpost.php?p=1454105&postcount=10

**Comment by adam-ainsworth** [comment]
That's great - thanks for the info!
